//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDRG_Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDRG_Analyzer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected. Please select a save file before creating a backup..
        /// </summary>
        internal static string BackupNoFileSelectedText {
            get {
                return ResourceManager.GetString("BackupNoFileSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup completed successfully! Your backup is saved as: .
        /// </summary>
        internal static string BackupSuccessText {
            get {
                return ResourceManager.GetString("BackupSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Achievements.
        /// </summary>
        internal static string button1_Text {
            get {
                return ResourceManager.GetString("button1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Websites.
        /// </summary>
        internal static string button2_Text {
            get {
                return ResourceManager.GetString("button2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to church-endSpotkanie2B.
        /// </summary>
        internal static string checkedListBox1_Items {
            get {
                return ResourceManager.GetString("checkedListBox1.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to church-endTheWorstEnd.
        /// </summary>
        internal static string checkedListBox1_Items1 {
            get {
                return ResourceManager.GetString("checkedListBox1.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to church-endIdontknow.
        /// </summary>
        internal static string checkedListBox1_Items2 {
            get {
                return ResourceManager.GetString("checkedListBox1.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to church-endJustGoThereGood.
        /// </summary>
        internal static string checkedListBox1_Items3 {
            get {
                return ResourceManager.GetString("checkedListBox1.Items3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to church-endJustGoThereBad.
        /// </summary>
        internal static string checkedListBox1_Items4 {
            get {
                return ResourceManager.GetString("checkedListBox1.Items4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-ballsexploded.
        /// </summary>
        internal static string checkedListBox2_Items {
            get {
                return ResourceManager.GetString("checkedListBox2.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-goodEnd1.
        /// </summary>
        internal static string checkedListBox2_Items1 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-genericSchizoEnd.
        /// </summary>
        internal static string checkedListBox2_Items10 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-KilledByADirtyCop1.
        /// </summary>
        internal static string checkedListBox2_Items11 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-KilledByADirtyCop2.
        /// </summary>
        internal static string checkedListBox2_Items12 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-theyKnowOblivious.
        /// </summary>
        internal static string checkedListBox2_Items13 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-theyKnow.
        /// </summary>
        internal static string checkedListBox2_Items14 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bigdaddyhurtSecretEpilogue.
        /// </summary>
        internal static string checkedListBox2_Items15 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saveEdited.
        /// </summary>
        internal static string checkedListBox2_Items16 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-badEnd1.
        /// </summary>
        internal static string checkedListBox2_Items2 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-badEnd2.
        /// </summary>
        internal static string checkedListBox2_Items3 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-badEnd3.
        /// </summary>
        internal static string checkedListBox2_Items4 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-badEnd4.1.
        /// </summary>
        internal static string checkedListBox2_Items5 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-badEnd4.2.
        /// </summary>
        internal static string checkedListBox2_Items6 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-healthEnd.
        /// </summary>
        internal static string checkedListBox2_Items7 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-fedEnd.
        /// </summary>
        internal static string checkedListBox2_Items8 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-schizoEnd.
        /// </summary>
        internal static string checkedListBox2_Items9 {
            get {
                return ResourceManager.GetString("checkedListBox2.Items9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string checkForUpdatesToolStripMenuItem_Size {
            get {
                return ResourceManager.GetString("checkForUpdatesToolStripMenuItem.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string checkForUpdatesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("checkForUpdatesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string commandsGroupBox_Text {
            get {
                return ResourceManager.GetString("commandsGroupBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;C:\system\debug\reports\report_1.txt&quot; --- Sys Report 1 Virus attack, DT?
        ///&quot;C:\system\debug\reports\report_2.txt&quot; --- Sys Report 2 - if 3, must be 2 and 1
        ///&quot;C:\system\debug\reports\report_3.txt&quot; --- Sys Report 3 - Found after prologue, cutscene of console.
        ///&quot;F:\files\research\journal\1574_12_12.txt&quot; --- Journal Text of Derry Tavis
        ///&quot;F:\Jun\system\safety\Asimov3.xftt&quot; --- Access Denied
        ///F:\files\research\journal\1578_12_16.txt
        ///F:\files\research\journal\1580_12_18.txt
        ///
        ///PlayVideo --- Uses file path to play a given  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string commandsTextBox_Text {
            get {
                return ResourceManager.GetString("commandsTextBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Backup.
        /// </summary>
        internal static string createBackupButton_Text {
            get {
                return ResourceManager.GetString("createBackupButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a Save File. The content of the Save File will be displayed here..
        /// </summary>
        internal static string debugTextBox_Text {
            get {
                return ResourceManager.GetString("debugTextBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string deutschToolStripMenuItem_Size {
            get {
                return ResourceManager.GetString("deutschToolStripMenuItem.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string donateToolStripMenuItem_Size {
            get {
                return ResourceManager.GetString("donateToolStripMenuItem.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string donateToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("donateToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Edit Info.
        /// </summary>
        internal static string editInfoButton_Text {
            get {
                return ResourceManager.GetString("editInfoButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice!.
        /// </summary>
        internal static string EditInfoButtonCaption {
            get {
                return ResourceManager.GetString("EditInfoButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Editing has been added, enjoy!.
        /// </summary>
        internal static string EditInfoButtonText {
            get {
                return ResourceManager.GetString("EditInfoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string englishToolStripMenuItem_Size {
            get {
                return ResourceManager.GetString("englishToolStripMenuItem.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string españolToolStripMenuItem_Size {
            get {
                return ResourceManager.GetString("españolToolStripMenuItem.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español (MT) | Spanish.
        /// </summary>
        internal static string españolToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("españolToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string exitToolStripMenuItem_Size {
            get {
                return ResourceManager.GetString("exitToolStripMenuItem.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exitToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("exitToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string extraCreditsButton_Text {
            get {
                return ResourceManager.GetString("extraCreditsButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Credits.
        /// </summary>
        internal static string ExtraCreditsCaption {
            get {
                return ResourceManager.GetString("ExtraCreditsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra credits go to
        ///
        ///MDRG Discord - Coding Help
        ///italy2003 / PixivID: 66835722 - Art
        ///bgrmystr2 - Linux Testing
        ///Xiaoye - Chinese, Spanish, and Portugese Translation
        ///You - For using the program :)
        ///
        ///The Creator of this Program, as well as Xiaoye (Chinese, Spanish, and Portugese Translation) are on the MDRG Discord Server. If there are translation errors or missing translations, please report these either on the MDRG Analyzer GitHub page by opening a new Issue, by posting in this (https://github.com/Wehr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtraCreditsText {
            get {
                return ResourceManager.GetString("ExtraCreditsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string fileToolStripMenuItem_Size {
            get {
                return ResourceManager.GetString("fileToolStripMenuItem.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string fileToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("fileToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a File.
        /// </summary>
        internal static string gameVersionBox_Text {
            get {
                return ResourceManager.GetString("gameVersionBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string GenericErrorCaption {
            get {
                return ResourceManager.GetString("GenericErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string GenericSuccessCaption {
            get {
                return ResourceManager.GetString("GenericSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not check for Update!
        ///
        ///Error:
        ///
        ///.
        /// </summary>
        internal static string GitResponseCouldNotCheckForUpdateText {
            get {
                return ResourceManager.GetString("GitResponseCouldNotCheckForUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not check for Update:
        ///
        ///Invalid version format..
        /// </summary>
        internal static string GitResponseInvalidVersionFormatText {
            get {
                return ResourceManager.GetString("GitResponseInvalidVersionFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new version found!.
        /// </summary>
        internal static string GitResponseNewestVersionCaption {
            get {
                return ResourceManager.GetString("GitResponseNewestVersionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already on the newest version..
        /// </summary>
        internal static string GitResponseNewestVersionText {
            get {
                return ResourceManager.GetString("GitResponseNewestVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update found!.
        /// </summary>
        internal static string GitResponseNewVersionAvailableCaption {
            get {
                return ResourceManager.GetString("GitResponseNewVersionAvailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version found!
        ///
        ///Your Version: .
        /// </summary>
        internal static string GitResponseNewVersionAvailableText1 {
            get {
                return ResourceManager.GetString("GitResponseNewVersionAvailableText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Newest Version: .
        /// </summary>
        internal static string GitResponseNewVersionAvailableText2 {
            get {
                return ResourceManager.GetString("GitResponseNewVersionAvailableText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Do you want to open GitHub to get the latest release?.
        /// </summary>
        internal static string GitResponseNewVersionAvailableText3 {
            get {
                return ResourceManager.GetString("GitResponseNewVersionAvailableText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        internal static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Cum.
        /// </summary>
        internal static string groupBox10_Text {
            get {
                return ResourceManager.GetString("groupBox10.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Stamina.
        /// </summary>
        internal static string groupBox11_Text {
            get {
                return ResourceManager.GetString("groupBox11.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string groupBox12_Text {
            get {
                return ResourceManager.GetString("groupBox12.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental Health.
        /// </summary>
        internal static string groupBox13_Text {
            get {
                return ResourceManager.GetString("groupBox13.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Slot.
        /// </summary>
        internal static string groupBox14_Text {
            get {
                return ResourceManager.GetString("groupBox14.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Values.
        /// </summary>
        internal static string groupBox15_Text {
            get {
                return ResourceManager.GetString("groupBox15.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Name.
        /// </summary>
        internal static string groupBox16_Text {
            get {
                return ResourceManager.GetString("groupBox16.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lust.
        /// </summary>
        internal static string groupBox17_Text {
            get {
                return ResourceManager.GetString("groupBox17.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sympathy.
        /// </summary>
        internal static string groupBox18_Text {
            get {
                return ResourceManager.GetString("groupBox18.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longing.
        /// </summary>
        internal static string groupBox19_Text {
            get {
                return ResourceManager.GetString("groupBox19.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Version.
        /// </summary>
        internal static string groupBox2_Text {
            get {
                return ResourceManager.GetString("groupBox2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mood.
        /// </summary>
        internal static string groupBox20_Text {
            get {
                return ResourceManager.GetString("groupBox20.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        internal static string groupBox21_Text {
            get {
                return ResourceManager.GetString("groupBox21.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cum in Pussy.
        /// </summary>
        internal static string groupBox22_Text {
            get {
                return ResourceManager.GetString("groupBox22.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cum in Ass.
        /// </summary>
        internal static string groupBox23_Text {
            get {
                return ResourceManager.GetString("groupBox23.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cum in Stomach.
        /// </summary>
        internal static string groupBox24_Text {
            get {
                return ResourceManager.GetString("groupBox24.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Values.
        /// </summary>
        internal static string groupBox25_Text {
            get {
                return ResourceManager.GetString("groupBox25.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Stage(3).
        /// </summary>
        internal static string groupBox26_Text {
            get {
                return ResourceManager.GetString("groupBox26.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        internal static string groupBox27_Text {
            get {
                return ResourceManager.GetString("groupBox27.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subs.
        /// </summary>
        internal static string groupBox28_Text {
            get {
                return ResourceManager.GetString("groupBox28.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Streamtime.
        /// </summary>
        internal static string groupBox29_Text {
            get {
                return ResourceManager.GetString("groupBox29.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Values.
        /// </summary>
        internal static string groupBox3_Text {
            get {
                return ResourceManager.GetString("groupBox3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted(2).
        /// </summary>
        internal static string groupBox30_Text {
            get {
                return ResourceManager.GetString("groupBox30.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        internal static string groupBox31_Text {
            get {
                return ResourceManager.GetString("groupBox31.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Donos.
        /// </summary>
        internal static string groupBox32_Text {
            get {
                return ResourceManager.GetString("groupBox32.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest Stream.
        /// </summary>
        internal static string groupBox33_Text {
            get {
                return ResourceManager.GetString("groupBox33.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted(2).
        /// </summary>
        internal static string groupBox34_Text {
            get {
                return ResourceManager.GetString("groupBox34.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        internal static string groupBox35_Text {
            get {
                return ResourceManager.GetString("groupBox35.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Came inside Vag.
        /// </summary>
        internal static string groupBox36_Text {
            get {
                return ResourceManager.GetString("groupBox36.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Came inside Ass.
        /// </summary>
        internal static string groupBox37_Text {
            get {
                return ResourceManager.GetString("groupBox37.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Came inside Mouth.
        /// </summary>
        internal static string groupBox38_Text {
            get {
                return ResourceManager.GetString("groupBox38.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Came outside.
        /// </summary>
        internal static string groupBox39_Text {
            get {
                return ResourceManager.GetString("groupBox39.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church Achievements.
        /// </summary>
        internal static string groupBox4_Text {
            get {
                return ResourceManager.GetString("groupBox4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gametime.
        /// </summary>
        internal static string groupBox40_Text {
            get {
                return ResourceManager.GetString("groupBox40.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted(2).
        /// </summary>
        internal static string groupBox41_Text {
            get {
                return ResourceManager.GetString("groupBox41.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        internal static string groupBox42_Text {
            get {
                return ResourceManager.GetString("groupBox42.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Slot.
        /// </summary>
        internal static string groupBox43_Text {
            get {
                return ResourceManager.GetString("groupBox43.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Slot.
        /// </summary>
        internal static string groupBox44_Text {
            get {
                return ResourceManager.GetString("groupBox44.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Slot.
        /// </summary>
        internal static string groupBox45_Text {
            get {
                return ResourceManager.GetString("groupBox45.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent in(1).
        /// </summary>
        internal static string groupBox46_Text {
            get {
                return ResourceManager.GetString("groupBox46.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Streams.
        /// </summary>
        internal static string groupBox47_Text {
            get {
                return ResourceManager.GetString("groupBox47.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Maid.
        /// </summary>
        internal static string groupBox48_Text {
            get {
                return ResourceManager.GetString("groupBox48.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times Lost.
        /// </summary>
        internal static string groupBox49_Text {
            get {
                return ResourceManager.GetString("groupBox49.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Achievements.
        /// </summary>
        internal static string groupBox5_Text {
            get {
                return ResourceManager.GetString("groupBox5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times Won.
        /// </summary>
        internal static string groupBox50_Text {
            get {
                return ResourceManager.GetString("groupBox50.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times Ran Away.
        /// </summary>
        internal static string groupBox51_Text {
            get {
                return ResourceManager.GetString("groupBox51.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chess.
        /// </summary>
        internal static string groupBox52_Text {
            get {
                return ResourceManager.GetString("groupBox52.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Chain.
        /// </summary>
        internal static string groupBox53_Text {
            get {
                return ResourceManager.GetString("groupBox53.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times Lost.
        /// </summary>
        internal static string groupBox54_Text {
            get {
                return ResourceManager.GetString("groupBox54.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times Won.
        /// </summary>
        internal static string groupBox55_Text {
            get {
                return ResourceManager.GetString("groupBox55.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times Lost.
        /// </summary>
        internal static string groupBox56_Text {
            get {
                return ResourceManager.GetString("groupBox56.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times Won.
        /// </summary>
        internal static string groupBox57_Text {
            get {
                return ResourceManager.GetString("groupBox57.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ML came in Mouth.
        /// </summary>
        internal static string groupBox58_Text {
            get {
                return ResourceManager.GetString("groupBox58.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cum Wasted.
        /// </summary>
        internal static string groupBox59_Text {
            get {
                return ResourceManager.GetString("groupBox59.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string groupBox6_Text {
            get {
                return ResourceManager.GetString("groupBox6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Search&quot;(4).
        /// </summary>
        internal static string groupBox60_Text {
            get {
                return ResourceManager.GetString("groupBox60.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinegara End(1).
        /// </summary>
        internal static string groupBox61_Text {
            get {
                return ResourceManager.GetString("groupBox61.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deathgrip End(1).
        /// </summary>
        internal static string groupBox62_Text {
            get {
                return ResourceManager.GetString("groupBox62.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times to Church.
        /// </summary>
        internal static string groupBox63_Text {
            get {
                return ResourceManager.GetString("groupBox63.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Mental Info(1).
        /// </summary>
        internal static string groupBox64_Text {
            get {
                return ResourceManager.GetString("groupBox64.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastHunger Info(1).
        /// </summary>
        internal static string groupBox65_Text {
            get {
                return ResourceManager.GetString("groupBox65.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Headpat at(1).
        /// </summary>
        internal static string groupBox66_Text {
            get {
                return ResourceManager.GetString("groupBox66.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Bot Talk(1).
        /// </summary>
        internal static string groupBox67_Text {
            get {
                return ResourceManager.GetString("groupBox67.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Interact.(1).
        /// </summary>
        internal static string groupBox68_Text {
            get {
                return ResourceManager.GetString("groupBox68.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last woke up at(1).
        /// </summary>
        internal static string groupBox69_Text {
            get {
                return ResourceManager.GetString("groupBox69.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money.
        /// </summary>
        internal static string groupBox7_Text {
            get {
                return ResourceManager.GetString("groupBox7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last church visit(1).
        /// </summary>
        internal static string groupBox70_Text {
            get {
                return ResourceManager.GetString("groupBox70.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last worked at(1).
        /// </summary>
        internal static string groupBox71_Text {
            get {
                return ResourceManager.GetString("groupBox71.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Credits.
        /// </summary>
        internal static string groupBox72_Text {
            get {
                return ResourceManager.GetString("groupBox72.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last cuddled at(1).
        /// </summary>
        internal static string groupBox73_Text {
            get {
                return ResourceManager.GetString("groupBox73.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Stream at(5).
        /// </summary>
        internal static string groupBox74_Text {
            get {
                return ResourceManager.GetString("groupBox74.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last outside at(1).
        /// </summary>
        internal static string groupBox75_Text {
            get {
                return ResourceManager.GetString("groupBox75.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last equipm. at(1).
        /// </summary>
        internal static string groupBox76_Text {
            get {
                return ResourceManager.GetString("groupBox76.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last sex at(1).
        /// </summary>
        internal static string groupBox77_Text {
            get {
                return ResourceManager.GetString("groupBox77.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nun Points(4,5).
        /// </summary>
        internal static string groupBox78_Text {
            get {
                return ResourceManager.GetString("groupBox78.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriestBot Point(4,5).
        /// </summary>
        internal static string groupBox79_Text {
            get {
                return ResourceManager.GetString("groupBox79.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino Tokens.
        /// </summary>
        internal static string groupBox8_Text {
            get {
                return ResourceManager.GetString("groupBox8.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday(1).
        /// </summary>
        internal static string groupBox80_Text {
            get {
                return ResourceManager.GetString("groupBox80.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Cum.
        /// </summary>
        internal static string groupBox9_Text {
            get {
                return ResourceManager.GetString("groupBox9.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide and Instructions.
        /// </summary>
        internal static string GuideAndInstructionsCaption {
            get {
                return ResourceManager.GetString("GuideAndInstructionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Backup: This is the first thing you should do. It will create a backup, not overwrite it (unless you have more than 2147483647 backups, which will error out... I think).
        ///
        ///Follow the entry numbering. For example: If the value is &quot;42,927&quot;, then use a decimal value like &quot;83,145&quot;.
        ///
        ///It is unknown if special characters break the Names, so to be safe, only use letters &quot;A-Z&quot; and &quot;a-z&quot;. If you have the time to test it, please open an issue with your findings on what works and what doesn&apos;t.
        ///
        ///It is recomm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GuideAndInstructionsText {
            get {
                return ResourceManager.GetString("GuideAndInstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        internal static string guideButton_Text {
            get {
                return ResourceManager.GetString("guideButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string helpToolStripMenuItem_Size {
            get {
                return ResourceManager.GetString("helpToolStripMenuItem.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string helpToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("helpToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program has run into the following error:
        ///
        ///.
        /// </summary>
        internal static string HttpRequestExceptionMessageText {
            get {
                return ResourceManager.GetString("HttpRequestExceptionMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error happened when automatically checking for an update:
        ///
        ///Error:
        ///.
        /// </summary>
        internal static string HttpRequestUnknownErrorMessageText {
            get {
                return ResourceManager.GetString("HttpRequestUnknownErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a File.
        /// </summary>
        internal static string infoSaveBox_Text {
            get {
                return ResourceManager.GetString("infoSaveBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string label1_Size {
            get {
                return ResourceManager.GetString("label1.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1) Cannot be changed, rent is always on Monday
        ///(2) Converted for readability, not an actual value
        ///(3) No support will be given if changed
        ///(4) In some way related to the Church Questline.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string label4_Size {
            get {
                return ResourceManager.GetString("label4.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1) Uses Game Time.
        /// </summary>
        internal static string label4_Text {
            get {
                return ResourceManager.GetString("label4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string label5_Location {
            get {
                return ResourceManager.GetString("label5.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string label5_Size {
            get {
                return ResourceManager.GetString("label5.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (5) Uses Game Time.
        /// </summary>
        internal static string label5_Text {
            get {
                return ResourceManager.GetString("label5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string label6_Size {
            get {
                return ResourceManager.GetString("label6.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to keep her safe (and filled).
        /// </summary>
        internal static string label6_Text {
            get {
                return ResourceManager.GetString("label6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get out get out get out get out get out get out get out get out get out get out.
        /// </summary>
        internal static string label6HorrorText {
            get {
                return ResourceManager.GetString("label6HorrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to keep her safe (and filled).
        /// </summary>
        internal static string label6NormalText {
            get {
                return ResourceManager.GetString("label6NormalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string label7_Size {
            get {
                return ResourceManager.GetString("label7.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1) Uses Game Time
        ///.
        /// </summary>
        internal static string label7_Text {
            get {
                return ResourceManager.GetString("label7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string languageToolStripMenuItem {
            get {
                return ResourceManager.GetString("languageToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string languageToolStripMenuItem_Size {
            get {
                return ResourceManager.GetString("languageToolStripMenuItem.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string languageToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("languageToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string lightswitchCheckbox_Location {
            get {
                return ResourceManager.GetString("lightswitchCheckbox.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string lightswitchCheckbox_Size {
            get {
                return ResourceManager.GetString("lightswitchCheckbox.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightswitch.
        /// </summary>
        internal static string lightswitchCheckbox_Text {
            get {
                return ResourceManager.GetString("lightswitchCheckbox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string loadToolStripMenuItem_Size {
            get {
                return ResourceManager.GetString("loadToolStripMenuItem.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load File....
        /// </summary>
        internal static string loadToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("loadToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Notice!.
        /// </summary>
        internal static string MachineLanguageNoticeCaption {
            get {
                return ResourceManager.GetString("MachineLanguageNoticeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The selected translation was machine translated.
        ///
        ///If you wish to help improve the translation, please contact Strawberry (@strawberrymk.vi) on the MDRG Discord Server, or open a GitHub Issue at https://github.com/Wehrmachtserdbeere/MDRG-Analyzer.
        ///
        ///When submitting fixes, please state the language and attach the corrected localization files:
        ///&lt;Form1.language.resx&gt; and &lt;Strings.language.resx&gt;..
        /// </summary>
        internal static string MachineLanguageNoticeText {
            get {
                return ResourceManager.GetString("MachineLanguageNoticeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDRG Files (*.mdrg)|*.mdrg|All Files (*.*)|*.*.
        /// </summary>
        internal static string openFileDialogFilter {
            get {
                return ResourceManager.GetString("openFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a .mdrg file..
        /// </summary>
        internal static string openFileDialogTitle {
            get {
                return ResourceManager.GetString("openFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string openReadmeToolStripMenuItem_Size {
            get {
                return ResourceManager.GetString("openReadmeToolStripMenuItem.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Readme.
        /// </summary>
        internal static string openReadmeToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("openReadmeToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string pictureBox1_Image {
            get {
                return ResourceManager.GetString("pictureBox1.Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string pictureBox2_Image {
            get {
                return ResourceManager.GetString("pictureBox2.Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string quickLinkToGitHubToolStripMenuItem_Size {
            get {
                return ResourceManager.GetString("quickLinkToGitHubToolStripMenuItem.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Link to GitHub.
        /// </summary>
        internal static string quickLinkToGitHubToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("quickLinkToGitHubToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0}.
        /// </summary>
        internal static string RadioButtonFileText {
            get {
                return ResourceManager.GetString("RadioButtonFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string reportABugToolStripMenuItem_Size {
            get {
                return ResourceManager.GetString("reportABugToolStripMenuItem.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a Bug.
        /// </summary>
        internal static string reportABugToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("reportABugToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool is made for the game &quot;!Ω Factorial Omega: My Dystopian Robot Girlfriend&quot;.
        ///
        ///WARNING - Spoilers! This tool will include spoilers by the fact that it lists a lot of information. Please be warned!
        ///
        ///To begin using it, select &quot;File&quot; -&gt; &quot;Open File&quot; and open your save file. Then select which slot you want to check. This does not include autosaves.
        ///
        ///Prior to 0.90, your save files were saved in the following directory:
        ///[ C:\Users\&lt;YOUR USERNAME&gt;\AppData\LocalLow\IncontinentCell\My Dystopian Robot Girlfriend [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string richTextBox1_Text {
            get {
                return ResourceManager.GetString("richTextBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The good ending&quot;.
        /// </summary>
        internal static string richTextBox12_Text {
            get {
                return ResourceManager.GetString("richTextBox12.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! This feature is in testing and your save will most likely be corrupted! Keep a backup!
        ///The options will be unlocked when you agree that you have read this text and acknowledge that any loss of data will be your fault, will be on you alone, and that this feature more likely than not corrupt the selected save, if not every save.
        ///.
        /// </summary>
        internal static string richTextBox2_Text {
            get {
                return ResourceManager.GetString("richTextBox2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;I don&apos;t Know&quot; Ending.
        /// </summary>
        internal static string richTextBox3_Text {
            get {
                return ResourceManager.GetString("richTextBox3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The oblivious ending&quot;.
        /// </summary>
        internal static string richTextBox4_Text {
            get {
                return ResourceManager.GetString("richTextBox4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The worst ending&quot;.
        /// </summary>
        internal static string richTextBox5_Text {
            get {
                return ResourceManager.GetString("richTextBox5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The not good enough ending&quot;.
        /// </summary>
        internal static string richTextBox6_Text {
            get {
                return ResourceManager.GetString("richTextBox6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending-ballsexploded --- &quot;Too much juice...&quot;
        ///ending-goodEnd1 --- &quot;Selling your bot&quot;
        ///ending-badEnd1 --- &quot;Termination of tenancy&quot;
        ///ending-badEnd2 --- &quot;Failure...&quot;
        ///ending-badEnd3 --- &quot;Coward...&quot;
        ///ending-badEnd4.1 --- &quot;Termination of tenancy v2: hobo&quot;
        ///ending-badEnd4.2 --- &quot;Termination of tenancy v2: murder&quot;
        ///ending-healthEnd --- &quot;Starvation&quot;
        ///ending-fedEnd --- &quot;Got caught...&quot;
        ///ending-schizoEnd --- &quot;I&apos;m not crazy...&quot;
        ///ending-genericSchizoEnd --- &quot;Wall-kun&quot;
        ///ending-KilledByADirtyCop1 --- &quot;Never trust the cops...&quot;
        ///ending [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string richTextBox7_Text {
            get {
                return ResourceManager.GetString("richTextBox7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save (Overwrites current save!).
        /// </summary>
        internal static string saveButton_Text {
            get {
                return ResourceManager.GetString("saveButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when loading your save. Please re-export your save and try again.
        ///
        ///If it still does not work, paste your save file into a &quot;JSON Beautifier&quot; and check if there is any data inside &quot;savedata&quot;. If there is not, your save might be corrupt.
        ///
        ///If there is data, and the program does not work, please contact me on the MDRG Discord Server (https://discord.com/invite/SwpQUFWreW), or open an Issue on GitHub (https://github.com/Wehrmachtserdbeere/MDRG-Analyzer).
        ///
        ///You have to reload the file via [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SavedataLoadingErrorText {
            get {
                return ResourceManager.GetString("SavedataLoadingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you tried to load doesn&apos;t contain any saved game data. This means that the save you are attempting to open is empty or not properly exported. Here&apos;s what you need to do to fix this:
        ///
        ///First, double-check that you actually exported your save correctly before trying to load it. If you&apos;re not sure, make sure you followed all the proper steps to export the save file. This is important because if the save hasn&apos;t been exported properly, it will not work when you try to load it.
        ///
        ///If you&apos;re sure you exp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SavedataLoadingNoSavedataErrorText {
            get {
                return ResourceManager.GetString("SavedataLoadingNoSavedataErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of your save file entries caused an integer overflow! Please fix this before trying to load it into the program.
        ///
        ///If your save is completely vanilla and has not been previously edited, open an Issue of message me on the MDRG Discord. Otherwise, you already know what you did, and I won&apos;t give your support for you breaking your own save..
        /// </summary>
        internal static string SavedataLoadingOverflowErrorText {
            get {
                return ResourceManager.GetString("SavedataLoadingOverflowErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program ran into an unknown error. Please contact me on Discord or open an Issue.
        ///
        ///Error:
        ///.
        /// </summary>
        internal static string SavedataLoadingUnknownError {
            get {
                return ResourceManager.GetString("SavedataLoadingUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while saving your file!
        ///
        ///Error:
        ///.
        /// </summary>
        internal static string SavedataSavingErrorText {
            get {
                return ResourceManager.GetString("SavedataSavingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File successfully saved!.
        /// </summary>
        internal static string SavedataSavingSuccessText {
            get {
                return ResourceManager.GetString("SavedataSavingSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string saveEditConsentBox_Size {
            get {
                return ResourceManager.GetString("saveEditConsentBox.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I acknowledge and understand that using this feature may result in breaking or compromising
        ///my save games, and I assume full responsibility for any potential loss of progress or data..
        /// </summary>
        internal static string saveEditConsentBox_Text {
            get {
                return ResourceManager.GetString("saveEditConsentBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Editing.
        /// </summary>
        internal static string saveEditGroupBox_Text {
            get {
                return ResourceManager.GetString("saveEditGroupBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Files.
        /// </summary>
        internal static string saveFilesChoosingBox_Text {
            get {
                return ResourceManager.GetString("saveFilesChoosingBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File.
        /// </summary>
        internal static string saveSlotBox_Text {
            get {
                return ResourceManager.GetString("saveSlotBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File.
        /// </summary>
        internal static string saveSlotBoxBot_Text {
            get {
                return ResourceManager.GetString("saveSlotBoxBot.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File.
        /// </summary>
        internal static string saveSlotBoxGen_Text {
            get {
                return ResourceManager.GetString("saveSlotBoxGen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string suggestAFeatureToolStripMenuItem_Size {
            get {
                return ResourceManager.GetString("suggestAFeatureToolStripMenuItem.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest a Feature.
        /// </summary>
        internal static string suggestAFeatureToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("suggestAFeatureToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string tabPage1_Text {
            get {
                return ResourceManager.GetString("tabPage1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Info.
        /// </summary>
        internal static string tabPage2_Text {
            get {
                return ResourceManager.GetString("tabPage2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string tabPage3_Text {
            get {
                return ResourceManager.GetString("tabPage3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websites.
        /// </summary>
        internal static string tabPage4_Text {
            get {
                return ResourceManager.GetString("tabPage4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string tabPage5_Text {
            get {
                return ResourceManager.GetString("tabPage5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Info.
        /// </summary>
        internal static string tabPage6_Text {
            get {
                return ResourceManager.GetString("tabPage6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Info.
        /// </summary>
        internal static string tabPage7_Text {
            get {
                return ResourceManager.GetString("tabPage7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Editing.
        /// </summary>
        internal static string tabPage8_Text {
            get {
                return ResourceManager.GetString("tabPage8.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string tabPage9_Text {
            get {
                return ResourceManager.GetString("tabPage9.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem Ipsum! English!.
        /// </summary>
        internal static string testString {
            get {
                return ResourceManager.GetString("testString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string toolStripSeparator1_Size {
            get {
                return ResourceManager.GetString("toolStripSeparator1.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string traditionalChineseToolStripMenuItem_Size {
            get {
                return ResourceManager.GetString("traditionalChineseToolStripMenuItem.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited Websites.
        /// </summary>
        internal static string visitedWebsiteGroupBox_Text {
            get {
                return ResourceManager.GetString("visitedWebsiteGroupBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cocktracts.ic/help.
        /// </summary>
        internal static string websitesCheckBoxes_Items10 {
            get {
                return ResourceManager.GetString("websitesCheckBoxes.Items10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cocktracts.ic/partner.
        /// </summary>
        internal static string websitesCheckBoxes_Items11 {
            get {
                return ResourceManager.GetString("websitesCheckBoxes.Items11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cocktracts.ic/partners.
        /// </summary>
        internal static string websitesCheckBoxes_Items12 {
            get {
                return ResourceManager.GetString("websitesCheckBoxes.Items12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cocktwitch.ic.
        /// </summary>
        internal static string websitesCheckBoxes_Items13 {
            get {
                return ResourceManager.GetString("websitesCheckBoxes.Items13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cocktwitch.ic/leaderboard.
        /// </summary>
        internal static string websitesCheckBoxes_Items14 {
            get {
                return ResourceManager.GetString("websitesCheckBoxes.Items14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cocktwitch.ic/stats.
        /// </summary>
        internal static string websitesCheckBoxes_Items15 {
            get {
                return ResourceManager.GetString("websitesCheckBoxes.Items15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bang.ic/email.
        /// </summary>
        internal static string websitesCheckBoxes_Items2 {
            get {
                return ResourceManager.GetString("websitesCheckBoxes.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cocktracts.ic/available.
        /// </summary>
        internal static string websitesCheckBoxes_Items8 {
            get {
                return ResourceManager.GetString("websitesCheckBoxes.Items8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cocktracts.ic/contract.
        /// </summary>
        internal static string websitesCheckBoxes_Items9 {
            get {
                return ResourceManager.GetString("websitesCheckBoxes.Items9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string WeekDaysFriday {
            get {
                return ResourceManager.GetString("WeekDaysFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string WeekDaysMonday {
            get {
                return ResourceManager.GetString("WeekDaysMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string WeekDaysSaturday {
            get {
                return ResourceManager.GetString("WeekDaysSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string WeekDaysSunday {
            get {
                return ResourceManager.GetString("WeekDaysSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string WeekDaysThursday {
            get {
                return ResourceManager.GetString("WeekDaysThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string WeekDaysTuesday {
            get {
                return ResourceManager.GetString("WeekDaysTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string WeekDaysUnknown {
            get {
                return ResourceManager.GetString("WeekDaysUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string WeekDaysWednesday {
            get {
                return ResourceManager.GetString("WeekDaysWednesday", resourceCulture);
            }
        }
    }
}
