//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDRG_Analyzer_Multi_Platform.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Achievements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Achievements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDRG_Analyzer_Multi_Platform.Resources.Achievements", typeof(Achievements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination of tenancy.
        /// </summary>
        internal static string ending_badend1 {
            get {
                return ResourceManager.GetString("ending_badend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure....
        /// </summary>
        internal static string ending_badend2 {
            get {
                return ResourceManager.GetString("ending_badend2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coward....
        /// </summary>
        internal static string ending_badend3 {
            get {
                return ResourceManager.GetString("ending_badend3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination of tenancy v2: hobo.
        /// </summary>
        internal static string ending_badend4_1 {
            get {
                return ResourceManager.GetString("ending_badend4.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination of tenancy v2: murder.
        /// </summary>
        internal static string ending_badend4_2 {
            get {
                return ResourceManager.GetString("ending_badend4.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too much juice....
        /// </summary>
        internal static string ending_ballsexploded {
            get {
                return ResourceManager.GetString("ending_ballsexploded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an ending by itself but part of &quot;They know...&quot; - Met bigdaddyhurt but didn&apos;t continue his storyline.
        /// </summary>
        internal static string ending_bigdaddyhurtSecretEpilogue {
            get {
                return ResourceManager.GetString("ending_bigdaddyhurtSecretEpilogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got caught....
        /// </summary>
        internal static string ending_fedend {
            get {
                return ResourceManager.GetString("ending_fedend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall-kun.
        /// </summary>
        internal static string ending_genericschizoend {
            get {
                return ResourceManager.GetString("ending_genericschizoend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling your bot.
        /// </summary>
        internal static string ending_goodend1 {
            get {
                return ResourceManager.GetString("ending_goodend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The good ending&quot;.
        /// </summary>
        internal static string ending_goodend2 {
            get {
                return ResourceManager.GetString("ending_goodend2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starvation.
        /// </summary>
        internal static string ending_healthend {
            get {
                return ResourceManager.GetString("ending_healthend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;I don&apos;t know&quot; Ending.
        /// </summary>
        internal static string ending_idontknow {
            get {
                return ResourceManager.GetString("ending_idontknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never trust the cops....
        /// </summary>
        internal static string ending_killedbyadirtycop1 {
            get {
                return ResourceManager.GetString("ending_killedbyadirtycop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never trust the cops... AGAIN.
        /// </summary>
        internal static string ending_killedbyadirtycop2 {
            get {
                return ResourceManager.GetString("ending_killedbyadirtycop2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The not good enough ending&quot;.
        /// </summary>
        internal static string ending_notgoodenough {
            get {
                return ResourceManager.GetString("ending_notgoodenough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The oblivious ending&quot;.
        /// </summary>
        internal static string ending_oblivious {
            get {
                return ResourceManager.GetString("ending_oblivious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used the iamacheater website..
        /// </summary>
        internal static string ending_saveedited {
            get {
                return ResourceManager.GetString("ending_saveedited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not crazy....
        /// </summary>
        internal static string ending_schizoend {
            get {
                return ResourceManager.GetString("ending_schizoend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They know....
        /// </summary>
        internal static string ending_theyknow {
            get {
                return ResourceManager.GetString("ending_theyknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They know... (oblivious).
        /// </summary>
        internal static string ending_theyknowoblivious {
            get {
                return ResourceManager.GetString("ending_theyknowoblivious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The worst ending.
        /// </summary>
        internal static string ending_worst {
            get {
                return ResourceManager.GetString("ending_worst", resourceCulture);
            }
        }
    }
}
