//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDRG_Analyzer_Multi_Platform.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Generic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Generic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDRG_Analyzer_Multi_Platform.Resources.Generic", typeof(Generic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string achievements {
            get {
                return ResourceManager.GetString("achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement unlocked.
        /// </summary>
        internal static string achievements_added {
            get {
                return ResourceManager.GetString("achievements_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained.
        /// </summary>
        internal static string achievements_obtained {
            get {
                return ResourceManager.GetString("achievements_obtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement locked.
        /// </summary>
        internal static string achievements_removed {
            get {
                return ResourceManager.GetString("achievements_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unobtained.
        /// </summary>
        internal static string achievements_unobtained {
            get {
                return ResourceManager.GetString("achievements_unobtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppData.
        /// </summary>
        internal static string appdata {
            get {
                return ResourceManager.GetString("appdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup successfully created.
        /// </summary>
        internal static string backupcreated {
            get {
                return ResourceManager.GetString("backupcreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining JSON.
        /// </summary>
        internal static string combining_json {
            get {
                return ResourceManager.GetString("combining_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commonly used paths.
        /// </summary>
        internal static string commonpaths {
            get {
                return ResourceManager.GetString("commonpaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Backup.
        /// </summary>
        internal static string createbackup {
            get {
                return ResourceManager.GetString("createbackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string currentlyediting {
            get {
                return ResourceManager.GetString("currentlyediting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        internal static string desktop {
            get {
                return ResourceManager.GetString("desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string documents {
            get {
                return ResourceManager.GetString("documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string downloads {
            get {
                return ResourceManager.GetString("downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved file. The file can be found at.
        /// </summary>
        internal static string filesavedat {
            get {
                return ResourceManager.GetString("filesavedat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key, please choose one of the existing options..
        /// </summary>
        internal static string invalidkey {
            get {
                return ResourceManager.GetString("invalidkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file.
        /// </summary>
        internal static string loadfile {
            get {
                return ResourceManager.GetString("loadfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input the directory in which the file you want to load is located. Alternatively, you can directly input a file..
        /// </summary>
        internal static string loadfile_instructions {
            get {
                return ResourceManager.GetString("loadfile_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file or directory was not found. Ensure any input file ends with &quot;.mdrg&quot;. Please try again..
        /// </summary>
        internal static string loadfile_invalid {
            get {
                return ResourceManager.GetString("loadfile_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &quot;.mdrg&quot; files were found in the specified directory..
        /// </summary>
        internal static string loadfile_nofilesfound {
            get {
                return ResourceManager.GetString("loadfile_nofilesfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one of these files.
        /// </summary>
        internal static string loadfile_selectoneofthesefiles {
            get {
                return ResourceManager.GetString("loadfile_selectoneofthesefiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string mainmenu {
            get {
                return ResourceManager.GetString("mainmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like you\&apos;re experiencing an issue where the \&quot;savedata\&quot; section of your savefile JSON appears to be empty. This might seem like a bug at first glance, but I want to reassure you that the program is working exactly as intended. The issue is not caused by a malfunction in the software but rather by a misunderstanding of how the save and load process is supposed to work.
        ///
        ///Let\&apos;s walk through this carefully and make sure everything is clear.
        ///
        ///When you open the savefile and notice that \&quot;savedata\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nosavedata {
            get {
                return ResourceManager.GetString("nosavedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact Strawberry Software on the official GitHub Repository by opening an Issue, by going on the official Strawberry Software Discord Server and pinging Strawberry, or by going to the MDRG Analyzer thread on the Incontinent Cell Discord Server and pinging Strawberry there..
        /// </summary>
        internal static string pleasecontactme {
            get {
                return ResourceManager.GetString("pleasecontactme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing JSON.
        /// </summary>
        internal static string preparing_json {
            get {
                return ResourceManager.GetString("preparing_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savefile Inspector.
        /// </summary>
        internal static string savefilemenu {
            get {
                return ResourceManager.GetString("savefilemenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        internal static string saving {
            get {
                return ResourceManager.GetString("saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving file.
        /// </summary>
        internal static string saving_file {
            get {
                return ResourceManager.GetString("saving_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the save slot you wish to load..
        /// </summary>
        internal static string selectsavefile {
            get {
                return ResourceManager.GetString("selectsavefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid save slot has been selected, please try again..
        /// </summary>
        internal static string selectsaveslot_invalidsaveslot {
            get {
                return ResourceManager.GetString("selectsaveslot_invalidsaveslot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Note.
        /// </summary>
        internal static string setnote {
            get {
                return ResourceManager.GetString("setnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Languages.
        /// </summary>
        internal static string settings_availablelanguages {
            get {
                return ResourceManager.GetString("settings_availablelanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Language.
        /// </summary>
        internal static string settings_defaultlanguage {
            get {
                return ResourceManager.GetString("settings_defaultlanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your desired default language to use the program with. Invalid entries default to English (United States of America)..
        /// </summary>
        internal static string settings_defaultlanguage_prompt {
            get {
                return ResourceManager.GetString("settings_defaultlanguage_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving settings. Log file created..
        /// </summary>
        internal static string settings_errorsavingsettings {
            get {
                return ResourceManager.GetString("settings_errorsavingsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the key for the setting you wish to change..
        /// </summary>
        internal static string settings_instructions {
            get {
                return ResourceManager.GetString("settings_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid language chosen, defaulting to English (United States of America).
        /// </summary>
        internal static string settings_invalidlanguage {
            get {
                return ResourceManager.GetString("settings_invalidlanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved settings! Returning to Main Menu..
        /// </summary>
        internal static string settings_saved {
            get {
                return ResourceManager.GetString("settings_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected.
        /// </summary>
        internal static string settings_youhaveselectedlanguage {
            get {
                return ResourceManager.GetString("settings_youhaveselectedlanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        internal static string slot {
            get {
                return ResourceManager.GetString("slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file location is generally discouraged from being used.
        /// </summary>
        internal static string thisfilelocationisdiscouraged {
            get {
                return ResourceManager.GetString("thisfilelocationisdiscouraged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements....
        /// </summary>
        internal static string toachievements {
            get {
                return ResourceManager.GetString("toachievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating achievements.
        /// </summary>
        internal static string updating_achievements {
            get {
                return ResourceManager.GetString("updating_achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating websites.
        /// </summary>
        internal static string updating_websites {
            get {
                return ResourceManager.GetString("updating_websites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday | Rent in 3 days.
        /// </summary>
        internal static string WeekDaysFriday {
            get {
                return ResourceManager.GetString("WeekDaysFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday | Rent today or in 7 days.
        /// </summary>
        internal static string WeekDaysMonday {
            get {
                return ResourceManager.GetString("WeekDaysMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday | Rent in 2 days.
        /// </summary>
        internal static string WeekDaysSaturday {
            get {
                return ResourceManager.GetString("WeekDaysSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday | Rent tomorrow.
        /// </summary>
        internal static string WeekDaysSunday {
            get {
                return ResourceManager.GetString("WeekDaysSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday | Rent in 4 days.
        /// </summary>
        internal static string WeekDaysThursday {
            get {
                return ResourceManager.GetString("WeekDaysThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday | Rent in 6 days.
        /// </summary>
        internal static string WeekDaysTuesday {
            get {
                return ResourceManager.GetString("WeekDaysTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string WeekDaysUnknown {
            get {
                return ResourceManager.GetString("WeekDaysUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday | Rent in 5 days.
        /// </summary>
        internal static string WeekDaysWednesday {
            get {
                return ResourceManager.GetString("WeekDaysWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to MDRG Analyzer (Multi-Platform)! While this is a secondary app to the main MDRG Analyzer, which is Windows-only, I hope you can use this for a natively supported workaround!.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
